const noticias = [
  {
    id: 'noticia-001',
    titulo: 'Nuevo recorrido nocturno en el Centro Histórico de Buenos Aires',
    descripcion: 'El gobierno porteño lanzó una nueva propuesta de free tour nocturno que recorre los edificios más emblemáticos del microcentro, con guías especializados en historia urbana y arquitectura colonial.',
    imagen: 'https://images.unsplash.com/photo-1589909202802-8f4aadce1849?w=800',
    url: 'https://www.turismo.buenosaires.gob.ar/noticias/nuevo-recorrido-nocturno-centro-historico',
    fechaPublicacion: '2026-04-20T10:00:00Z',
    categoria: 'free tour',
    actividadRelacionadaId: 1,
  },
  {
    id: 'noticia-002',
    titulo: 'Cataratas del Iguazú entre los diez destinos más visitados de América Latina en 2026',
    descripcion: 'Un informe de la Organización Mundial del Turismo posicionó a las Cataratas del Iguazú en el top 10 de los destinos más populares de la región, con un récord de visitantes en el primer trimestre del año.',
    imagen: 'https://images.unsplash.com/photo-1598302936227-ca73f7432eeb?w=800',
    url: 'https://www.argentina.gob.ar/turismo/noticias/cataratas-iguazu-top-10-america-latina-2026',
    fechaPublicacion: '2026-04-15T08:30:00Z',
    categoria: 'excursión',
    actividadRelacionadaId: 2,
  },
  {
    id: 'noticia-003',
    titulo: 'Palermo se consolida como el barrio gastronómico más innovador de Buenos Aires',
    descripcion: 'Nuevos restaurantes de cocina de autor y bodegas urbanas se suman a la oferta de Palermo, que este año incorporó más de 30 locales que fusionan la cocina argentina con influencias internacionales.',
    imagen: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
    url: 'https://www.clarin.com/viajes/palermo-barrio-gastronomico-innovador-buenos-aires_0_2026.html',
    fechaPublicacion: '2026-04-10T12:00:00Z',
    categoria: 'experiencia gastronómica',
    actividadRelacionadaId: 3,
  },
  {
    id: 'noticia-004',
    titulo: 'Temporada de trekking en el Aconcagua: récord de permisos solicitados para 2026',
    descripcion: 'La Dirección de Recursos Naturales de Mendoza informó que los permisos de ascenso al Cerro Aconcagua superaron por primera vez los 8.000 en una sola temporada, con gran presencia de turistas europeos y asiáticos.',
    imagen: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    url: 'https://www.mendoza.gov.ar/turismo/noticias/record-permisos-aconcagua-2026',
    fechaPublicacion: '2026-04-05T09:15:00Z',
    categoria: 'aventura',
    actividadRelacionadaId: 4,
  },
  {
    id: 'noticia-005',
    titulo: 'El MALBA presenta una nueva sala dedicada al arte latinoamericano contemporáneo',
    descripcion: 'El Museo de Arte Latinoamericano de Buenos Aires inauguró una sala permanente con obras de artistas emergentes de Argentina, Brasil y México, que ya puede visitarse en el recorrido guiado habitual.',
    imagen: 'https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=800',
    url: 'https://www.malba.org.ar/noticias/nueva-sala-arte-latinoamericano-contemporaneo',
    fechaPublicacion: '2026-04-01T11:00:00Z',
    categoria: 'visita guiada',
    actividadRelacionadaId: 5,
  },
  {
    id: 'noticia-006',
    titulo: 'Los free tours en Buenos Aires baten récord de participantes durante Semana Santa',
    descripcion: 'Durante la última Semana Santa los recorridos gratuitos por el centro porteño congregaron a más de 12.000 turistas nacionales e internacionales, consolidando esta modalidad como la más popular entre los visitantes jóvenes.',
    imagen: 'https://images.unsplash.com/photo-1575783970733-1aaedde1db74?w=800',
    url: 'https://www.infobae.com/turismo/2026/04/record-free-tours-buenos-aires-semana-santa',
    fechaPublicacion: '2026-03-28T14:00:00Z',
    categoria: 'free tour',
    actividadRelacionadaId: 1,
  },
  {
    id: 'noticia-007',
    titulo: 'Iguazú lanza nuevos senderos accesibles para personas con movilidad reducida',
    descripcion: 'El Parque Nacional Iguazú habilitó tres circuitos adaptados con rampas y plataformas elevadas que permiten a personas con silla de ruedas acceder a las vistas principales de las cataratas sin restricciones.',
    imagen: 'https://images.unsplash.com/photo-1570135489919-2c62c42e5c63?w=800',
    url: 'https://www.parquesnacionales.gob.ar/noticias/iguazu-senderos-accesibles-2026',
    fechaPublicacion: '2026-03-22T10:30:00Z',
    categoria: 'excursión',
    actividadRelacionadaId: 2,
  },
  {
    id: 'noticia-008',
    titulo: 'Argentina figura en la guía Michelin por primera vez con restaurantes de Buenos Aires',
    descripcion: 'Tres establecimientos del barrio de Palermo obtuvieron mención especial en la edición latinoamericana de la guía Michelin 2026, destacando el uso de productos regionales y técnicas de cocina de vanguardia.',
    imagen: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
    url: 'https://www.lanacion.com.ar/lifestyle/argentina-guia-michelin-palermo-restaurantes_2026',
    fechaPublicacion: '2026-03-15T09:00:00Z',
    categoria: 'experiencia gastronómica',
    actividadRelacionadaId: 3,
  },
  {
    id: 'noticia-009',
    titulo: 'Mendoza apuesta al turismo de aventura con nuevas rutas de senderismo en la Cordillera',
    descripcion: 'La provincia de Mendoza presentó un plan de inversión para señalizar y equipar 15 nuevas rutas de montaña en los alrededores del Aconcagua, orientadas a excursionistas de nivel intermedio.',
    imagen: 'https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=800',
    url: 'https://www.mendoza.gov.ar/turismo/noticias/nuevas-rutas-senderismo-cordillera-2026',
    fechaPublicacion: '2026-03-08T08:00:00Z',
    categoria: 'aventura',
    actividadRelacionadaId: 4,
  },
  {
    id: 'noticia-010',
    titulo: 'Los museos porteños incorporan recorridos en realidad aumentada para sus visitas guiadas',
    descripcion: 'El MALBA y otros cinco museos de Buenos Aires adoptaron tecnología de realidad aumentada en sus visitas guiadas, permitiendo a los visitantes ver obras restauradas digitalmente y obtener contexto histórico en tiempo real desde su teléfono.',
    imagen: 'https://images.unsplash.com/photo-1503152394-c571994fd383?w=800',
    url: 'https://www.telam.com.ar/notas/202604/museos-buenos-aires-realidad-aumentada-visitas-guiadas',
    fechaPublicacion: '2026-03-01T13:00:00Z',
    categoria: 'visita guiada',
    actividadRelacionadaId: 5,
  },
];

export async function fetchNoticias() {
  return noticias;
}
